# k8s/frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: inventario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend       # ← Coincide con tus NetworkPolicies
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend-egi:latest
          imagePullPolicy: Never   # Imagen cargada localmente en Minikube
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: frontend-config
            - secretRef:
                name: frontend-secret
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: inventario
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: inventario
data:
  MYSQL_HOST: "mysql-service"
  MYSQL_PORT: "3306"
  MYSQL_DB:   "inventario_itu"
  MYSQL_USER: "mate"
  MONGO_HOST: "mongodb-service"
  MONGO_PORT: "27017"
  LDAP_HOST:  "ldap://openldap-service"
  LDAP_BASE_DN: "dc=itu,dc=edu,dc=ar"
---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
  namespace: inventario
type: Opaque
stringData:
  MYSQL_PASSWORD: "itu12345"
  SECRET_KEY:     "itu-egi-secret-2024"