apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: inventario
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3MxMjM=
  MYSQL_DATABASE:      aW52ZW50YXJpb19pdHU=
  MYSQL_USER:          YXBwdXNlcg==
  MYSQL_PASSWORD:      YXBwcGFzczQ1Ng==