apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-config
  namespace: inventario-egi
data:
  LDAP_ORGANISATION: "Instituto Tecnologico Universitario"
  LDAP_DOMAIN: "itu.edu.ar"
  LDAP_BASE_DN: "dc=itu,dc=edu,dc=ar"
  LDAP_HOST: "ldap-service"
  LDAP_PORT: "389"
