apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-config
  namespace: inventario-egi
data:
  LDAP_ORGANISATION: "Instituto Tecnologico Universitario"
  LDAP_DOMAIN: "itu.local"
  LDAP_BASE_DN: "dc=itu,dc=local"
