apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: inventario-egi
  labels:
    app: inventario-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventario-app
  template:
    metadata:
      labels:
        app: inventario-app
    spec:
      containers:
        - name: inventario-app
          image: inventario-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MYSQL_PASSWORD
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MONGO_PASSWORD
            - name: LDAP_BIND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: LDAP_BIND_PASSWORD
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: JWT_SECRET_KEY
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
