apiVersion: v1
kind: Service
metadata:
  name: inventario-app-service
  namespace: inventario-egi
spec:
  type: NodePort
  selector:
    app: inventario-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080
